num1= float(input("Enter the First Number:"))
num2= float(input("Enter the Second Number:"))
Addition= (num1+ num2)
print(f"Addition:{Addition}")
Subtraction=(num1 - num2)
print(f"Subtraction:{Subtraction}")
Multiplication= (num1 * num2)
print(f"Multiplication:{Multiplication}")
Division= (num1/num2)
print(f"Division:{Division}")
